### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by KristjanKr** [TeamMD5/ProjectX#3]
Game crashes on startup, saying about projextx
log: https://paste.ee/p/U7hRS

**Comment by KitsuneAlex** [comment]
that issue is already opened by hextrace, thanks for the report but please look if there's already an issue like this next time

**Comment by hextrace** [comment]
Just in case, since I didn't mention the issue here - the actual report went under [NineTailLib](https://github.com/TeamMD5/NineTailLib/issues/6).

**Comment by KristjanKr** [comment]
Yeah, i was confused for a second because couldn't see the issue, but then after KitsuneAlex said to look around, i saw it was in NineTailLib.
